# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

Test:
  stage: test
  script:
    - npm install
    - npm run test-coverage

Deploy:
  stage: deploy
  script:
    - echo 'Prepare for deploying to Heroku...'
    - apt-get update
    - apt-get install ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=rise-to-the-top --api-key=$HEROKU_API_KEY
  only:
    - production
